---
abstract: 'make simple lightweight record-like structures'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Fatal: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Struct-Dumb
provides:
  Struct::Dumb:
    file: lib/Struct/Dumb.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
